/** 
  * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/  

(function evenFibsLessThanFourMillion() {
  var previousNumber = 0,
      currentNumber = 1,
      maxValue = 4000000,
      sum = 0,
      tempCurrentNumber;

  while (previousNumber + currentNumber < maxValue) {
    if ((previousNumber + currentNumber) % 2 === 0) {
      sum += previousNumber + currentNumber;
    }
    tempCurrentNumber = currentNumber;
    currentNumber += previousNumber;
    previousNumber = tempCurrentNumber;
  }

  console.log(sum);

})();

